### ISSUE TITLE
Request for input of inference

### ISSUE THREAD

**Issue by czy20000902** [microsoft/Swin3D#10]
Hello, I'm trying to run the `segmentation.py` and found that the input file `examples/input.npz` is not in this repo, could you please upload it?

**Comment by Yukichiii** [comment]
Sure, it is just a voxelized scannet data for unittest: [input.npz](https://drive.google.com/file/d/10DnuXSLCc0tzIMy9p5kEaCsWUXZZWtP3/view?usp=sharing)

For downstream task, please refer to this repo [Swin3D_Task](https://github.com/Yukichiii/Swin3D_Task)

**Comment by czy20000902** [comment]
Thanks a lot. 
I've just encountered another problem. I'm using voxelized input for a segmentation task. When I was trying to use the Swin3D backbone, the `sp` and `coords_sp` would have different `shape[0]` resulting in the size not match error. If I force `coords_sp` to be compressed with the same `shape[0]` as `sp`, then the downsample would fail.
Do you have any suggestion about this?

**Comment by Yukichiii** [comment]
The `coords_sp` is used for Contextual relative signal encoding(cRSE), 
`coords_sp.C` should be the same as `sp.C`, `coords_sp.F` stores the signal used for encoding of each voxel. Why would it be different shapes? If the `sp` is a voxelized input, `coords_sp` should also be voxelized accordingly.

To keep `sp` and `coords_sp` consistent after downsample, please specify coords_sp with shared `coordinate_map_key `and `coordinate_manager`.

```
coords_sp = SparseTensor(features=cRSE, coordinate_map_key=sp.coordinate_map_key, 
coordinate_manager=sp.coordinate_manager)
```

**Comment by czy20000902** [comment]
Thanks for the reply. It seems I was focusing on the `SparseTensor` but ignored the input.
I just found out that I got the feature shape wrong as I modified the `segmentation` code a little for not using normal vectors. Now the code is functioning well. 
Have a nice day!
