### ISSUE TITLE
Does the pretrained model apply for both GridKNNDownsample and GridDownsample?

### ISSUE THREAD

**Issue by czy20000902** [microsoft/Swin3D#12]
Hello, I have a question about the pretrained model.

When I set `knn_down` to False for `Swin3DUNet`, the IoU appeared to be pretty low even after loading the pretrained model. Does it apply for both `GridKNNDownsample` and `GridDownsample` or only `GridKNNDownsample`? 

If it's the latter, may I ask for a `GridDownsample` version? Thanks.

**Comment by Yukichiii** [comment]
Our pretrained model uses only `GridKNNDownsample` for better segmentation result.
Sorry that we do not have the `GridDownsample` version, you can pretrain it on Structured3D.

**Comment by yuxiaoguo** [comment]
Please feel free to contact us for any further issues.
