### ISSUE TITLE
s3ds 6-fold

### ISSUE THREAD

**Issue by 3019234115** [microsoft/Swin3D#14]
can you provide the 6-fold code on s3ds? I will appreciate it very much !

**Comment by Yukichiii** [comment]
You can refer to the [Task Repo](https://github.com/Yukichiii/Swin3D_Task), and modify the  `DATA.test_area` in `swin3D_RGB_S.yaml` or `swin3D_RGB_L.yaml` to each fold of 6-fold cross-validation and collect the corresponding results.
