### ISSUE TITLE
ScanNet v2 - Normals

### ISSUE THREAD

**Issue by hpc100** [microsoft/Swin3D#21]
Thanks for providing this work !

Why use Swin3D_RGB_N.py when PointGroup's preprocessing code does not provide normals ?

**Comment by Yukichiii** [comment]
I'm sorry, I didn't understand your question. Could you please describe your problem more specifically?

**Comment by hpc100** [comment]
Than'ks for the quick response.

For ScanNet,  Swin3D_RGB_N.py is used. So I assume you have normals for ScanNet. However the PointCloud code does not write the normals in ".pth".
Do you use normals for ScanNet ? And if so, where did you get them ?

**Comment by Yukichiii** [comment]
The ScanNet dataset provides mesh data from which the vertex normal can be computed. In fact, the original ScanNet benchmark is defined on the vertices of these mesh.

**Comment by hpc100** [comment]
@Yukichiii , yes but if we follow the PointGroup method, we don't have the normals in the "..._inst_nostuff.pth" files. Did you use any code to retrieve the normals ?

**Comment by mrsempress** [comment]
How do we get normals from mesh? Is there any code for this?

**Comment by Yukichiii** [comment]
You can use `trimesh` or other libraries to calculate the vertex normals of a triangle mesh.
