### ISSUE TITLE
vote？

### ISSUE THREAD

**Issue by hfutdzx** [microsoft/Swin3D#25]
the great work，now，i am following your work for my work. but i don’t understand a sentence from paper. the sentence is “On the ScanNet benchmark(test dataset), we ensembled the results of three trained models by voting the prediction on over-segmented meshes”.
 you set vote_num=12，but here is 3？

I have an understanding, but I don't know if it's correct or not. vote_num means same weight trained model but different input. “three trained model” mean same model but different weight，every trained model have vote_num=12,therefore 3 x12=36？

**Comment by Yukichiii** [comment]
Yes. `vote_num` refers to the times of augmentations of the same model for an input scene during the testing phase. Ensemble refers to voting on the final predictions using different models.

**Comment by hfutdzx** [comment]
thank you very much
