### ISSUE TITLE
Details about Using Swin3D Backbone with CAGroup in 3D Detection

### ISSUE THREAD

**Issue by Felicia-fang** [microsoft/Swin3D#26]
Hi! I am curious about the training details for the Swin3D encoder and CAGroup. Since the CAGroup uses a repeated ScanNet dataset during the training process, I am wondering if there are different implementations in the dataset. Additionally, when using a 48-dimensional upsampling output as the CAGroup input, the CUDA memory overflows even on a 24GB 4090 GPU, and this occurs despite setting the batch size to 1. Could you provide some insights into the training environment for the 3D detection task? Thank you!

**Comment by Yukichiii** [comment]
During training, the input scenes can be cut into chunks, which can effectively reduce memory consumption.
