### ISSUE TITLE
Codes of finetuing in downstream task

### ISSUE THREAD

**Issue by linhaojia13** [microsoft/Swin3D#7]
According to Sec.5.2 in the paper, it seems that for fine-tuning on the 3D Detection task, I just need to replace the backbone in the FCAF3D and CAGroup3D code repositories with Swin3D and load the weights, is that correct?

As for fine-tuning on the semantic segmentation task on S3DIS and ScanNet, the paper doesn't mention which code repository it was developed based on. Could you please consider opening the fine-tuning codes?

**Comment by yuxiaoguo** [comment]
The release of Swin3D contains two parts:
1. The implementation of Swin3D backbone, including the code of backbone network, memory efficient implementation and cRSE. This part is released as the current repo -- [Swin3D](https://github.com/microsoft/Swin3D).
2. The down-streaming tasks of indoor scene understanding, including segmentation and detection tasks in ScanNetv2 and S3DIS datasets. We divide this part into the other repo: [Swin3D_Task](https://github.com/Yukichiii/Swin3D_Task/tree/main). However, the repo is under the final test to make sure everything goes well. Once we finishing test, we will officially add the link in [Swin3D](https://github.com/microsoft/Swin3D) homepage.

**Comment by linhaojia13** [comment]
Thank you very much!
