### ISSUE TITLE
How to apply Swin3D as backbone to detect 3d objects? 

### ISSUE THREAD

**Issue by Pioneer12138** [microsoft/Swin3D#9]
hey! I want to know how to apply SWIN3D for 3d object detection? The provided code seems to be designed for semantic segmentation. I would like to know if it can be directly used as a backbone for object detection?

**Comment by Yukichiii** [comment]
For 3d object detection tasks, we replace the backbone of FCAF3D, CAGroup3D or other detectors with `Swin3DEncoder` in `Swin3D/models/Swin3D.py` to extract multi-level feature.  You can refer to these detectors in [mmdetection3d](https://github.com/open-mmlab/mmdetection3d) or [OpenPCDet](https://github.com/open-mmlab/OpenPCDet).
The code and models of our downstream task will be released in this repo([Swin3D_Task](https://github.com/Yukichiii/Swin3D_Task)). The 3d object detection part is being re-organized.
